### ISSUE TITLE
Recommend SPDX as the preferred list of licenses

### ISSUE THREAD

**Issue by jdvorak001** [openaire/guidelines-cris-managers#134]
In line with the current [DataCite Metadata Kernel v.4.4](https://schema.datacite.org/meta/kernel-4.4/doc/DataCite-MetadataKernel_v4.4.pdf), p.28, we should recommend the [SPDX](https://spdx.org/licenses/) URIs, e.g. http://spdx.org/licenses/CC-BY-4.0 . The `scheme` would then be https://spdx.org/licenses/ .

This should also be demonstrated in examples. One Publication example needs migration.

**Comment by ACz-UniBi** [comment]
Dear @jdvorak001 ,

to propose the use of the License element in _Publications_ 

`					<License scheme="https://spdx.org/licenses">https://spdx.org/licenses/CC-BY-3.0</License>`

I would also suggest an example in the _Products_ for the record of [**Product id="Products/729487"**](https://github.com/openaire/guidelines-cris-managers/blob/4f006c04410ada74a4af551227d42f81966f0afd/samples/openaire_cerif_xml_example_products.xml#L55) like 

`                                        <License scheme="https://spdx.org/licenses">https://spdx.org/licenses/CC0-1.0</License>`
