### ISSUE TITLE
broken link at 'CRIS information elements relevant for OpenAIRE'

### ISSUE THREAD

**Issue by ACz-UniBi** [openaire/guidelines-cris-managers#138]
The reference [1] 'https://www.coar-repositories.org/activities/repository-interoperability/coar-vocabularies/deliverables/'  at https://openaire-guidelines-for-cris-managers.readthedocs.io/en/v1.1.1/cris_elements_openaire.html page is giving at 404 response code from the COAR website

![image](https://user-images.githubusercontent.com/41193035/177698082-ce7bff0b-5a80-4c32-8760-ceb57ee996f4.png)

**Comment by ACz-UniBi** [comment]
This could be updated to 'https://vocabularies.coar-repositories.org/resource_types/' instead of 'https://www.coar-repositories.org/activities/repository-interoperability/coar-vocabularies/deliverables/'.

**Comment by jdvorak001** [comment]
Thank you @ACz-UniBi for spotting and correcting this one!
