### ISSUE TITLE
validation failure in openaire_cerif_xml_example_projects.xml

### ISSUE THREAD

**Issue by ACz-UniBi** [openaire/guidelines-cris-managers#141]
Some feedback points us to an issue in the XML example file:  samples/openaire_cerif_xml_example_projects.xml

The namespace of

`xmlns="https://www.openaire.eu/cerif-profile/vocab/OpenAIRE_Funding_Types"`

isn't defined.

**Comment by ACz-UniBi** [comment]
To solve the issue, please add in the _xsi:schemaLocation_

  https://www.openaire.eu/cerif-profile/vocab/OpenAIRE_Funding_Types https://www.openaire.eu/schema/cris/current/vocabularies/openaire_funding_types.xsd

Replace the whole attribute with

`xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd https://www.openaire.eu/cerif-profile/1.1/ https://www.openaire.eu/schema/cris/current/openaire-cerif-profile.xsd https://www.openaire.eu/cerif-profile/vocab/OpenAIRE_Funding_Types https://www.openaire.eu/schema/cris/current/vocabularies/openaire_funding_types.xsd"`

The example will be updated soon.

**Comment by jdvorak001** [comment]
I'm surprised this should be needed, with regard to the [xs:import instruction in the main OpenAIRE schema](https://github.com/openaire/guidelines-cris-managers/blob/298b87dbef95386fe265a4d650b13dcd1a56425a/schemas/openaire-cerif-profile.xsd#L19).

I know some parsers may be puzzled at relative links. I'll try to prepend ``./`` to make these schema links easier to recognize. Hopefully it resolves the original reporter's problem.
