### ISSUE TITLE
snapshot release of coar access rights vocabulary

### ISSUE THREAD

**Issue by joschirr** [openaire/guidelines-cris-managers#15]
I made a 
commit coar-repositories/vocabularies@42b07ffed16c7cae2c4b040a8090bb7c91da319d
of a snapshot of the coar access rights vocabulary, so you may want to include it in CERIF.

**Comment by joschirr** [comment]
new snapshot release:
commit coar-repositories/vocabularies@f3b87b21c0eb65eaaae785f7724504122f833f20
which now contains the concept definitions and label translations from english to turkish, spanish, french, japanese, german

**Comment by jdvorak001** [comment]
Had been processed and committed on 2017-05-23.
