### ISSUE TITLE
Add ReadTheDocs configuration file

### ISSUE THREAD

**Issue by jdvorak001** [openaire/guidelines-cris-managers#151]
The [ReadTheDocs project page of the Guidelines](https://readthedocs.org/projects/openaire-guidelines-for-cris-managers/versions/) tells us that:
> Your project(s) "openaire-guidelines-for-cris-managers" don't have a configuration file. Configuration files will soon be required by projects, and will no longer be optional. [Read our blog post to create one](https://blog.readthedocs.com/migrate-configuration-v2/) and ensure your project continues building successfully.

**Comment by ACz-UniBi** [comment]
Thank you @jdvorak001 for highlighting this.

[How to add a configuration file](https://docs.readthedocs.io/en/stable/guides/setup/configuration-file.html) for ReadTheDocs.

**Comment by jdvorak001** [comment]
The file seems to work, no more complaints from ReadTheDocs. Thank you @ACz-UniBi!
