### ISSUE TITLE
ListMetadataFormats vs. Service Compatibility statements from Identify

### ISSUE THREAD

**Issue by jdvorak001** [openaire/guidelines-cris-managers#153]
While preparing the 1.2 release I got puzzled by the [Compatibility](https://openaire-guidelines-for-cris-managers-development.readthedocs.io/en/latest/cerif_xml_service_entity.html#compatibility) classifications inside the `Service` CERIF element in the response to the OAI-PMH 2.0 Identify request.

We currently have the following levels defined:
- OpenAIRE Guidelines 1.2 compatible CRIS (https://www.openaire.eu/cerif-profile/vocab/OpenAIRE_Service_Compatibility#1.2): CRIS compatible with OpenAIRE Guidelines for CRIS managers version 1.2
- OpenAIRE Guidelines 1.1.1 compatible CRIS (https://www.openaire.eu/cerif-profile/vocab/OpenAIRE_Service_Compatibility#1.1.1): CRIS compatible with OpenAIRE Guidelines for CRIS managers version 1.1.1
- OpenAIRE Guidelines 1.1 compatible CRIS (https://www.openaire.eu/cerif-profile/vocab/OpenAIRE_Service_Compatibility#1.1): CRIS compatible with OpenAIRE Guidelines for CRIS managers version 1.1
- OpenAIRE Guidelines 1.0 compatible CRIS (https://www.openaire.eu/cerif-profile/vocab/OpenAIRE_Service_Compatibility#1.0): CRIS compatible with OpenAIRE Guidelines for CRIS managers version 1.0

I'm finding this inconsistent. We should either:

*(A)* Define the admissible compatibility levels codes at the finest versions, defined by the released versions of the Guidelines so far (i.e. **1.0**, **1.1.0**, **1.1.1**, **1.2.0**).

*(B)* Be happy with having compatibility levels at the minor versions (i.e. **1.0**, **1.1**, **1.2**), so get rid of 1.1.1.

In any case the [Validator](https://github.com/EuroCRIS/openaire-cris-validator) should check consistency between these compatibility statements and the OAI-PMH 2.0 metadata formats declared by the endpoint in response to ListMetadataFormats requests.

I personally do not see much value in having the micro version level compatibility statements, as we committed ourselves to backwards compatibility within the minor versions.

**Comment by ACz-UniBi** [comment]
Dear @jdvorak001 , thank you for raising this. I notice that the [Compatibility](https://openaire-guidelines-for-cris-managers.readthedocs.io/en/v1.1.1/cerif_xml_service_entity.html#compatibility) classification inside the 'Service' entity at v1.1.1, there is only 2 classifications

* OpenAIRE Guidelines 1.1 compatible CRIS (https://www.openaire.eu/cerif-profile/vocab/OpenAIRE_Service_Compatibility#1.1): CRIS compatible with OpenAIRE Guidelines for CRIS managers version 1.1
* OpenAIRE Guidelines 1.0 compatible CRIS (https://www.openaire.eu/cerif-profile/vocab/OpenAIRE_Service_Compatibility#1.0): CRIS compatible with OpenAIRE Guidelines for CRIS managers version 1.0

I would support the _(B)_ option as this already supports backward compatibility within version 1.1 (v1.1.0 and v1.1.1).

**Comment by jdvorak001** [comment]
Correct! The 1.1.1 compatibility was actually added _after_ the 1.1.1 release. If we keep the backwards compatibility of the micro versions, this compatibility level is not needed.

O.k., I'll go for option _(B)_. 

I'll also add additional rules in the validator that will require a metadata format in the ListMetadataFormats response if the corresponding compatibility level was declared in the Identify response (for the 1.1 and 1.2 compatibility levels).

**Comment by jdvorak001** [comment]
Fixed in 1.2.0
