### ISSUE TITLE
Example: patent

### ISSUE THREAD

**Issue by jdvorak001** [openaire/guidelines-cris-managers#18]

**Comment by jdvorak001** [comment]
@lremy volunteered to do this one.

**Comment by lremy** [comment]
There could be some issues regarding the classifications of patents.
I identified two source of classifications:

- International Patent Classification: http://www.wipo.int/classifications/ipc/en/
- Cooperative Patent Classification: https://www.cooperativepatentclassification.org/index.html

I didn't found any uri or url for these classifications, which could be a problem regarding #11 with cfGenericClassification__Type being a URI.

**Comment by lremy** [comment]
Also, I use the Link entity to provide some linkage between patents, which could be a problem regarding #35 .

**Comment by jdvorak001** [comment]
Laurent, many thanks!

**Comment by lremy** [comment]
New element Predecessors created within the xsd + correction of the URIs for the classifications.

**Comment by jdvorak001** [comment]
This has been adopted, thanks @lremy for your contributions!
