### ISSUE TITLE
Split the COAR Resource Types vocabulary into three separate type classifications

### ISSUE THREAD

**Issue by jdvorak001** [openaire/guidelines-cris-managers#2]
CERIF has the following three result entities:
- ResultPublication
- ResultPatent
- ResultProduct
They represent different kinds of research outputs. All of them come in the scope of the updated Guidelines.

In order to avoid inconsistencies, we should provide separate type classifications for each of these entities. A first shot is the following:

1. Everything under "Text" except "Patent" goes to COAR Publication Types.
2. "Patent" goes to COAR Patent Types (single entry classification for now).
3. "Text" itself does not go anywhere.
4. Everything else goes to COAR Product Types.

Does this appear reasonable to you?

**Comment by joschirr** [comment]
I have two doubts.
1) By splitting the classifications it may require additional effort once an update of the resource type vocabulary is released
2) ""Text" itself does not go anywhere." But how to map "Text" if it's tagged with a resource?

**Comment by jdvorak001** [comment]
ad 1. This logic would be embedded in the XSLT stylesheet we're already using for mapping the concept scheme into a CERIF XML Schema file. I'd say this maintenance burden would be bearable.

ad 2. Indeed, this was a bit sloppy. Improved suggestion: "Text" goes to COAR Publication Types as a single top-level concept.

**Comment by joschirr** [comment]
ok.

**Comment by jdvorak001** [comment]
Thank for the feedback. So the ruleset is going to be the following:

1. "Text" and everything under it except "Patent" goes to COAR Publication Types.
2. "Patent" goes to COAR Patent Types (a single entry classification for now).
3. Everything else goes to COAR Product Types.

**Comment by jdvorak001** [comment]
resolved in commit fc093d7ef7b2a4bb3789bf05a3b5b43e0d4c6656

**Comment by jdvorak001** [comment]
resolved in commit fc093d7ef7b2a4bb3789bf05a3b5b43e0d4c6656
