### ISSUE TITLE
using controlled vocabularies with machine readable URIs and human readable literals/labels

### ISSUE THREAD

**Issue by joschirr** [openaire/guidelines-cris-managers#20]
@jdvorak001 , @abollini ,
when looking at the publication entity sample I wonder why the URIs of e.g. the COAR vocabularies are used as XML values.
Maybe this is fine as long as CERIF entities are consumed by machines only, but in order to target machines as well as humans do you think it would be feasible to put the concept-URI in an XML attribute and use the concept-label (e.g. preferred label in english) as the value of the XML field?

**Comment by jdvorak001** [comment]
@joschirr ,
CERIF XML has a slightly different convention to the same effect: The URI is in the element contents and next to it there is a XML comment that holds the human-readable label. E.g.
`<pubtypes:Type>http://purl.org/coar/resource_type/c_6501<!-- journal article --></pubtypes:Type>`

**Comment by jdvorak001** [comment]
@joschirr ,
As discussed in our call on May 10, this should be sufficient. 
The XML Schema imposes a strict validation of the URIs, allowing only the ones from the vocabulary.
The XML comment is there basically for debugging, while machine consumers will direct themselves by the URIs.
