### ISSUE TITLE
Allow ISSNs and ISBNs to be qualified as either print or online

### ISSUE THREAD

**Issue by jdvorak001** [openaire/guidelines-cris-managers#23]
In parallel with https://github.com/openaire/guidelines-literature-repositories/issues/2 and also in line with https://doi.org/10.1016/j.procs.2014.06.008

**Comment by jdvorak001** [comment]
We need to support possibly multiple ISSNs and ISBNs.

Do we also need the Linking ISSN (ISSN-L)? See [here](http://www.issn.org/understanding-the-issn/assignment-rules/the-issn-l-for-publications-on-multiple-media/).

**Comment by joschirr** [comment]
from the perspective of a single bibliographic record the ISSN-L might not be needed.

**Comment by jdvorak001** [comment]
In fact, ISSNs will be specified for records of type 'journal'. 
Would ISSN-L be relevant there?

**Comment by jdvorak001** [comment]
O.k., that makes the task a bit easier.

**Comment by jdvorak001** [comment]
It appears the ISSN International Centre is aiming at publishing their data online, see http://www.issn.org/understanding-the-issn/assignment-rules/issn-linked-data-application-profile/ .

The [document](http://www.issn.org/wp-content/uploads/2017/12/ISSN-LinkedDataApplicationProfile-v0_9.pdf) is currently in version 0.9 and the URLs are not working yet, but there is a good chance they will eventually.

For our purpose, we might re-use the 
http://issn.org/vocabularies/Medium concept scheme with the following contents:

1. http://issn.org/vocabularies/Medium#Print (paper),
2. http://issn.org/vocabularies/Medium#Online (online publication),
3. http://issn.org/vocabularies/Medium#DigitalCarrier (CD-ROM, USB keys) or 
4. http://issn.org/vocabularies/Medium#Other (Loose-leaf publications, braille, etc.)

Hopefully ISBNs can be served with the same classification.

**Comment by jdvorak001** [comment]
The above was agreed for ISSNs in the 2018-05-04 call.

**Comment by jdvorak001** [comment]
For ISBNs there is the EDItEUR (http://www.editeur.org – "international group coordinating development of the standards infrastructure for electronic commerce in the book, e-book and serials sectors") ONIX ontology which has a codelist for "Product forms" (see http://www.editeur.org/files/ONIX%20for%20books%20-%20code%20lists/ONIX_BookProduct_Codelists_Issue_41.html, search for "List 150").
However, that list is very detailed. It would be usable for a library information system, but not for our purpose of referencing the Work (FRBR). We may be well off using the same four-item scheme as for ISSNs.
