### ISSUE TITLE
openaire-oai-pmh-sets

### ISSUE THREAD

**Issue by wilkos-dans** [openaire/guidelines-cris-managers#24]
Hi all, According to: http://openaire-guidelines-for-cris-managers.readthedocs.io/en/latest/implementation.html#openaire-oai-pmh-sets
the entire graph setSpec should be named: **'openaire_cris'**.
A child like publications should have setSpec name: **'openaire_cris_publications'**.
Why not use a colon [:] as delimiter for parent and child set, like described in the[ oai-pmh specs](https://www.openarchives.org/OAI/openarchivesprotocol.html#Set)?:
The setSpec for publications would then become: **'openaire_cris:publications'**?

**Comment by jdvorak001** [comment]
That sounds like a good suggestion, we'll discuss it. Thanks, Wilko!

**Comment by abollini** [comment]
Hi @wilkos-dans , yes it looks the proper why to manage that from the oai-pmh specification perspective.
I'm worried about the actual implementation of such part of the specification in the existent platforms, as I don't want to raise the burden of adoption.
My understanding is that DSpace, Zenodo and Dataverse currently don't expose their internal hierarchical structure using parent/child oai-pmh sets this could mean that implementation could be harder for such communities or buggy. I haven't checked EPrints for instance.

My understanding is that using the parent:child the only practical benefit will be that only the most accurate set (the publication one) can be included in the OAI-PMH records but this could lead to bugs where asking for the parent set the record is not retrieved. Again this is just a speculation as the specification says clearly that this should work but as I never see it implemented I'm worried about the benefits vs risks balance here.

**Comment by jdvorak001** [comment]
As a possible way out of this conundrum I would propose that the full contents of the CRIS ("The entire graph of CERIF entities in the source CRIS system of relevance to OpenAIRE") is not defined as a set. It's the full contents the CRIS wishes to expose, so there in fact is no restriction, so we don't actually have to name this as a set.

Do you think this could possibly help?

**Comment by wilkos-dans** [comment]
Yes, I think this should work out fine. After all, all the entities should live in the top-level (no setname) of the repository anyway, whether using sets, or not.

**Comment by jdvorak001** [comment]
In fact we came to the conclusion that the `openaire_cris` set is not useful. Its contents should indeed be the union of all records from the per-entity sets with specifications  `openaire_cris_*`.

However, such collection is rather difficult to produce (specifically, to support paging, a.k.a. flow control) and, much more important, it is not easy to harvest. In fact, harvesters are much more likely to query the per-entity subsets where they know how to process the specific entity they will receive.

So my suggestion to use the implicit (unnamed) set was just a partial remedy. It fails short where the CRIS manager wishes to expose to OpenAIRE only a part of the publications, datasets, projects and the other objects that the CRIS records. Then the unnamed set would in fact require the CRIS to have a separate OAI-PMH endpoint for these Guidelines. That could be seen as an obstacle to implementing the Guidelines.

So we will **delete this set** altogether from the specification. Harvesters will have to issue separate requests for the 10 per-entity sets (or just some of them, depending on the purpose of the harvester).
