### ISSUE TITLE
Person FederatedIdentifiers

### ISSUE THREAD

**Issue by wilkos-dans** [openaire/guidelines-cris-managers#25]
Hi all, are there any plans or possibilities on extending the FederatedIdentifier's of a Person?
Only ORCID type seems to be allowed?

**Comment by jdvorak001** [comment]
@wilkos-dans , thanks for the feedback!

After discussing this in the editorial team we came to the conclusion that we need to allow a much wider range of person identifier types. The identifier types should, however, be from a controlled vocabulary i.e., not entirely amorphous.

Which additional identifier types did you have in mind?

**Comment by wilkos-dans** [comment]
Hi @jdvorak001 . I agree on a controlled list. Why not start with, ISNI, ResearcherID, Scopus authorId? Perhaps VIAF and Digital Author identifier (mainly NL-based)? Would be nice to be able to use a nameidentifierscheme/URI on a generic nameidentifier element?

**Comment by jdvorak001** [comment]
Hi @wilkos-dans , we took a look at it and devised a refactored version of the XML Schema, to be seen at https://github.com/openaire/guidelines-cris-managers/tree/identifiers-expanded . The person identifiers are isolated in a single file, https://github.com/openaire/guidelines-cris-managers/blob/identifiers-expanded/schemas/includes/person-identifiers.xsd , now containing ORCID, ResearcherID, Scopus Author ID and ISNI.

It should be relatively easy to file GitHub pull requests in case an additional identifier type is needed. May I suggest that you go ahead and try it with the DAI? ;-)

**Comment by jdvorak001** [comment]
The identifiers-expanded branch merged into master.
