### ISSUE TITLE
Placement of the Linking Relationships

### ISSUE THREAD

**Issue by jdvorak001** [openaire/guidelines-cris-managers#28]
In order to avoid potentially huge records and high update rates of these records, we introduce the following guideline for the placement of linking relationships:

> Keep the links as parts of the records on just one side of the relationships; choose the side that is likely to have smaller cardinality and is more stable.

For instance, the links that represent employment of a Person in an OrgUnit should be kept embedded in the Person records. We want to avoid an OrgUnit record containing the list of its current and past employees, as that is potentially huge and likely to change often.

This also holds for the recursive links. We want an OrgUnit record contain its parent OrgUnit (ideally the whole chain up to the level of the whole organisation). But we do not want the OrgUnit expose the list of subordinate OrgUnits (let alone with a breakdown to the level of individual departments or research groups).

We introduce this guideline having regard to the purpose of this CERIF profile, which basically should support mirroring the CRIS metadata in a harvester. APIs with other purposes may (and are likely to) take differring design decisions.

(This resulted from the call 2018-03-29, AB+JD+LR.)

**Comment by lremy** [comment]
Here is an analysis of the actual status of the relations between elements: [review spreadsheet](https://docs.google.com/spreadsheets/d/12NS0x1Gqfz2sXXPDP1mF3LQy05ZjOnlYCzhFGNd10FM/edit?usp=sharing)

This table must be read in columns: for example, the Funding element in the xsd file is the Funding column, containing references to Person, OrgUnit, Project. etc. The semantic used for the relations has been written down for each relation.
In red, a proposed links to be removed. An additionnal task should be planned for adding new relations.

**Comment by jdvorak001** [comment]
Laurent, thanks for the spreadsheet, it's very useful.
Let's discuss this in today's call.

**Comment by jdvorak001** [comment]
In the call we re-arranged the rows and columns of the spreadsheet to get an upper-triangular (well, almost: up to the result entities, see below) matrix.

We have identified the following ordering of entities where an entity XML record contains references to the earlier-listed ones, but not vice versa:

1. OrgUnit
2. Person
3. Funding
4. Project
5. Event
6. Equipment
7. Publication+Product+Patent
8. (Service)

The result entities (Publication, Product, Patent) are acting as one group because of their mutual "References" links.
For the limitations of the Service entity see #29.
