### ISSUE TITLE
Eliminate the generic <Link>s and <Classification>s from the examples

### ISSUE THREAD

**Issue by jdvorak001** [openaire/guidelines-cris-managers#35]

**Comment by lremy** [comment]
I found the corresponding references to Link and Classification elements.

Link tag
- projects
  - link to Funding with type=Contract for projects 112345 and 112346
    - solution: this link can be removed as the funding type Contract is already indicated within the Funding object in Funded/As
- orgunits
  - link to Funding with type=Funder for orgunit 310001
    - solution: this link can be removed as the link between Funding and OrgUnit with type=Funder is to be stored within the Funding regarding #28
  - links to Project with type=Partner for orgunit 312346
    - solution: these links can be removed as the link between Project and OrgUnit with type=Partner is to be stored within the Project regarding #28
  - links to Project with type=Coordinator for orgunit 312345
    - solution: these links can be removed as the link between Project and OrgUnit with type=Coordinator is to be stored within the Project regarding #28

Classification tag
- orgunits
  - scheme=OrganisationTypes for orgunits 312345, 312346, 310001 and 301250
    - solution: add a Type element for orgunit, same as for Project for example
  - scheme=? for orgunit 312347; it seems to be some information about the geographical location (see NUTS region  https://tbed.org/eudemo/index.php?tablename=nuts3_vw&function=details&where_field=nuts_code&where_value=EL303)
    - solution: remove these two elements from the sample until it is clear what this information exactly means in this context
- fundings and projects
  - scheme=OpenAIREOpenAccessRequirements for fundings 612347, 612351, 612352 and 612353 / projects 112345, 112346 and 112347
    - solution: I'm not familiar with that one, but it is not clear if that concept is linked to the project or the funding, this needs to be clarified first; one solution could then be to introduce a new element within Project or Funding
    - note: within the projects samples, there are Classification elements that represent references to the classifications of referenced Fundings (lines 66, 155 and 234); these references can be deleted
- publications
  - scheme=685b398c-6246-4aab-9507-7f533e4085ae for publications 812348 and 4123451
    - solution: I did not found this uuid within the CERIF1.5 semantics! It seems to be the language of the publication; a solution could be to introduce a Language element for the publication.
    - note: within the publications samples, there is a Classification element that represent a reference to the classification of a referenced OrgUnit (line 228); thi reference can be deleted
