### ISSUE TITLE
Leave out Patent/Identifier, confusing

### ISSUE THREAD

**Issue by jdvorak001** [openaire/guidelines-cris-managers#39]
We're having a generic identifier construct in Patent, but that's unlikely going to be used: the PatentNumber is another field.

**Comment by jdvorak001** [comment]
The construct is creating confusion among early implementors.
I'm suggesting to leave it out. Other views?

**Comment by lremy** [comment]
The patent number seems the only identifier for a patent.
There is something in ORCID about patents (https://orcid.org/blog/2016/09/12/meet-lens-integrating-orcid-ids-patents), but the id seems to be linked not to the patent directly but to the whole available data around the patent.
I agree with leaving it out. If we meet some case in the future where there is a need for other identifiers, we can put it back with a specific comment to warn users to keep the patent number in its specific element.

**Comment by jdvorak001** [comment]
Thanks, @lremy , I'll leave it out.
