### ISSUE TITLE
Open Access Mandates

### ISSUE THREAD

**Issue by lremy** [openaire/guidelines-cris-managers#40]
So far we have been recording if a funding (a funding programme/subprogramme, a call, or a specific funding of a project) or a project has any OA mandate or not.
We could - after PASTEUR4OA (http://www.pasteur4oa.eu/) and with ROARMAP (http://roarmap.eprints.org/) - make a step further and give the URL of the mandate that applies.

**Comment by lremy** [comment]
Specifications (avoid the use of the `<Classification>` tag, according to #35 ):
* ok
	* `<OAmandate mandated="true" url="http://example.com"/>`
	* `<OAmandate mandated="true"/>`
	* `<OAmandate mandated="false"/>`
* nok
	* `<OAmandate mandated="false" url="http://example.com"/>`

Possible solutions are described [here](https://www.w3.org/wiki/Value-equals_test_required).
* Schematron seems to be a [possible solution](https://www.w3.org/wiki/Value-equals_test_required#Check_clause) for this

**Comment by jdvorak001** [comment]
O.k., I find this a good solution. @abollini ?

**Comment by abollini** [comment]
I'm ok with Schematron too. Thanks
