### ISSUE TITLE
Adding of new compatibility level?

### ISSUE THREAD

**Issue by ACz-UniBi** [openaire/guidelines-cris-managers#55]
Dear,

some CRISes have compatibility to the new version 1.1.1 and present this in the field:

```
<Compatibility>
https://www.openaire.eu/cerif-profile/vocab/OpenAIRE_Service_Compatibility#1.1.1
</Compatibility>
```

Best, Andreas

**Comment by ACz-UniBi** [comment]
added in the commit 'e64a251'.

**Comment by jdvorak001** [comment]
While preparing the 1.2.0 release we agreed not to have compatibility statements at the micro level, just the minor one: **1.0**, **1.1**, **1.2**. Micro releases shall be backwards compatible.
