### ISSUE TITLE
Clarify requirements about referential integrity and not managed entities

### ISSUE THREAD

**Issue by abollini** [openaire/guidelines-cris-managers#56]
In the Implementation section of the guidelines we have included a notice that is IMHO not enough evident (or clear) across the guidelines

https://openaire-guidelines-for-cris-managers.readthedocs.io/en/v1.1.1/implementation.html

> In the extreme case where just the display name of a person or an organisation is known, the DisplayName with an empty Person or OrgUnit XML element can be used. However, it is recommended that CRIS managers keep curated authority lists everywhere where these are feasible.

Me and @jdvorak001 have discussed that during a CERIF TG meeting and it appears that we were not completely aligned about the implication. According to @jdvorak001 the xsd allow a lower complexity than what I originally assume, more specifically 

1. if an institution doesn't manage person can just put an **empty person tag** as an author or can use a person tag **without ID** to include more information about the author that are stored at the publication level, i.e. ORCID
2. the same concept **should apply to any other referred entity** such as the publication channel (no id for unmanaged journals, etc.) or unmanaged project

If we agree about such interpretation we should revisit the guideline to make it more explicit and link to this notice in all the place where a linked entity is embedded (person in publication, in project, etc.)

**Comment by jdvorak001** [comment]
Yes, we agree on that. We need to better explain the various options, ranging from:
```xml 
<Author>
  <DisplayName>Dvořák, J.</DisplayName>
  <Person/>
</Author>
```
up to:
```xml
<Author>
  <DisplayName>Dvořák, J.</DisplayName>
  <Person id="b7be2d0e-a7fc-46cf-a783-5a3a0964951a">
    <PersonName>
      <FamilyNames>Dvořák</FamilyNames>
      <FirstNames>Jan</FirstNames>
    </PersonName>
    <ORCID>https://orcid.org/0000-0001-8985-152X</ORCID>
    <ResearcherID>R-8048-2016</ResearcherID>
  </Person>
</Author>
```

**Comment by abollini** [comment]
After further discussion with @jdvorak001 it seems also useful to add crosslink to the 
https://openaire-guidelines-for-cris-managers.readthedocs.io/en/v1.1.1/implementation.html#metadata-representation-in-cerif-xml

> While syntactically, the CERIF profile XML allows to construct structures of any depth, the contents of each metadata record should be kept limited to the nearest objects that are representable by a top-level element. These neighboring objects should be expressed using as much detail as is practical to identify them. This includes links to any higher level structures of which the object is part, e.g. to an institution of which an organisation unit is part.
> 
> However, the neighboring object XML shall never contain more information or different information from what is expressed in the main record for that object i.e., where the object is retrieved as a top-level object. This is a stronger form of a requirement of functional dependency.

More specifically, the Person record eventually embedded in the Author tag of a publication should not include any affiliation information. The affiliation tag inside the author tag should instead keep all the OrgUnit up to the root organisation including for intermediate level only the name and identifiers.

I will prepare a PR to address that in the next weeks

**Comment by jdvorak001** [comment]
This appears to have been resolved. The addition of Medium in #150 verified the fix very thoroughly. I'm therefore closing this issue.
