### ISSUE TITLE
unambiguous reference to files for publication and product

### ISSUE THREAD

**Issue by abollini** [openaire/guidelines-cris-managers#59]
In the current CRIS guidelines there is no immediate, unambiguous way, to express the URL of a publication or product content (fulltext, rawdata file) and its access level (we have a single access tag only for the "whole publication / main content").
This is a clear deficiency compared to the latest Literature Repository guidelines 
https://openaire-guidelines-for-literature-repository-managers.readthedocs.io/en/v4.0.0/field_filelocation.html
that have updated this aspect.

Institution that use a single system for the repository and the CRIS system should be able to express the full richness of their content just with the CRIS guidelines without the need to support also the literature repository guidelines (or at least it should be sufficient for OpenAIRE to use only the CRIS profile to collect all the information).

**Comment by jdvorak001** [comment]
We'll extend the current Publication, Product and Patent XML elements with a new element \<**FileLocation**\> (0-n occurrences) to contain the reference to the file, with additional qualifications by access rights, mimetype and object type, as in the File Location field from the Literature Repository guidelines.

A note for documentation: discourage people from putting links into \<URL\>, they should try to place them in more specific places first. A good use of \<URL\> might be the link to the publisher landing page (or PDF file) in the absence of a DOI.

**Comment by jdvorak001** [comment]
We should follow the route of the 4.0 version of the Literature Repository Guidelines.

**Comment by jdvorak001** [comment]
Needed for #98

**Comment by jdvorak001** [comment]
Recording our today's discussion:

A `<FileLocation>` element containing the URI, with additional attributes for:
- `accessRights`
- description of the embargo period:
  - either `embargoEndDate` (in case of embargoed access), or 
  - the `dateAccepted` (~startDate) and `dateAvailable` (~endDate) (as modelled in the Data Archive guidelines and the DataCite schema) to express the full period of the embargo
- the information about the license structured after 16.a–d of the DataCite Metadata Kernel schema 4.4 _(but this may in some cases be multiple, common in software) – should this block the implementation, we'd postpone it_

**Comment by jdvorak001** [comment]
Additional discussion with @ACz-UniBi :

- Information about license should follow the syntax recommended in #134.
- The syntax for the per-file dates should follow #84 as closely as is practical.

This unfortunately prevents us from having all this as attributes on a single `<FileLocation>` element that would contain just the URI. We'd need an internal structure.

To be further discussed.
