### ISSUE TITLE
Which identifier schema for the organization website?

### ISSUE THREAD

**Issue by abollini** [openaire/guidelines-cris-managers#64]
In our example we left a FIXME, see
https://github.com/openaire/guidelines-cris-managers/blob/v1.1/samples/openaire_cerif_xml_example_orgunits.xml#L23

do we have a identifier schema for that?

**Comment by lremy** [comment]
maybe a first question would be: do we consider the website of an organization as an identifier?
Certainly it is unique, but couldn't it be used as an identifier for various objects (or type of objects)?

Consider https://github.com/openaire/guidelines-cris-managers/blob/f717ca324630db0e0619998e13d8af08689478b4/samples/openaire_cerif_xml_example_orgunits.xml#L80, which name is "European Commission", with identifier https://europa.eu/ (is that the same identifier as https://europa.eu ?), which is the official website of the European Union, including several institutions and bodies, and not only the European Commission.

**Comment by jdvorak001** [comment]
An initial list of identification systems relevant for the research domain:

Id System | Website | Operator | Sample Id | Regex pattern
---------- | -------- | --------- | ---------- | --------------
ROR | https://ror.org/ | ROR Project | |
GRID | https://grid.ac/ | Digital Science | | 
ISNI | http://www.isni.org/ | | 
FundRef Registry | https://www.crossref.org/services/funder-registry/ | Crossref | |
Ringgold Id | https://www.ringgold.com/ | Ringgold (commercial) | |
Global Legal Entity Identifier | https://www.gleif.org/en/ | | |
VAT Nr. | | Tax authorities | |

Some of these would be good candidates for inclusion as specific elements in the Guidelines.

**Comment by chenejac** [comment]
https://docs.google.com/document/d/1FmgPkoPd2gzgvdOZzbNZ4ine_gjQcsWHfOWcmU5pD_w/edit?usp=sharing

**Comment by jdvorak001** [comment]
The line in the example needs a fix: `<ElectronicAddress>`

**Comment by jdvorak001** [comment]
The OrgUnit identifiers should make it in a separate hand-written file like https://github.com/openaire/guidelines-cris-managers/blob/v1.1/schemas/includes/publication-identifiers.xsd

**Comment by jdvorak001** [comment]
I believe this has also been resolved, closing.
