### ISSUE TITLE
More information about Journals?

### ISSUE THREAD

**Issue by abollini** [openaire/guidelines-cris-managers#65]
Should we allow institution to expose the Journal Acronym? should we put that in the "publication" subtitle?

German institution sometimes have the ZDB ID of the Journal should we add this identifier type?

**Comment by joschirr** [comment]
> Should we allow institution to expose the Journal Acronym? should we put that in the "publication" subtitle?

ok, if "publication" element is about the journal
> 
> German institution sometimes have the ZDB ID of the Journal should we add this identifier type?
ok, yes.

**Comment by jdvorak001** [comment]
> > Should we allow institution to expose the Journal Acronym? should we put that in the "publication" subtitle?
> 
> ok, if "publication" element is about the journal

I'd be a worried about using one field for a slightly different piece of information. Abbreviation is something we are already having with projects, so I adding it here would not be a big issue.

> > German institution sometimes have the ZDB ID of the Journal should we add this identifier type?
> 
> ok, yes.

Yes. Preferably we have a regular expression to check valid values, such as in https://github.com/openaire/guidelines-cris-managers/blob/20f3535ce4493d19f3bf62a9bc9783ae7c4281ce/schemas/includes/person-identifiers.xsd#L106-L114

**Comment by jdvorak001** [comment]
For the journal abbreviation we can use cfResPublNameAbbrev ("a formal abbreviation system used for service provision").

**Comment by jdvorak001** [comment]
The ZDB identifier, see https://www.wikidata.org/wiki/Property:P1042

**Comment by jdvorak001** [comment]
@lremy

**Comment by jdvorak001** [comment]
This has been handled already, I believe.
