### ISSUE TITLE
No validator is mentioned in the guidelines.

### ISSUE THREAD

**Issue by ACz-UniBi** [openaire/guidelines-cris-managers#67]
20190717 Wilkos-dans | OAI-PMH for Harvesting | 

No validator (https://github.com/jdvorak001/openaire-cris-validator) is mentioned in the guidelines.This is a crucial part for the implementation of the guidelines.

**Comment by jdvorak001** [comment]
We can put in a link to current information (of all kinds) at https://github.com/openaire/guidelines-cris-managers#readme . That way we won't need to change the Guidelines document when there is news about the official OpenAIRE Validator.

**Comment by jdvorak001** [comment]
The prototype validator is mentioned in the README.md file, so closing.
