### ISSUE TITLE
What is CRIS?

### ISSUE THREAD

**Issue by vemonet** [openaire/guidelines-cris-managers#80]
I found the term of `CRIS` (managers) at multiple place in the OpenAIRE guidelines/specifications/documentation:
* OpenAIRE "website" :
https://www.openaire.eu/write-a-blogpost/openaire-guidelines-for-cris-managers-release-1-1-1?Itemid=2068&highlight=WyJjcmlzIl0=
* Documentation: https://guidelines.openaire.eu/en/latest/cris/index.html
* We can find also a ["scientific" publication](https://www.sciencedirect.com/science/article/pii/S1877050914007960) with `CRIS` in the title. Here again the term CRIS is used in the abstract without being defined: "This contribution focuses on a specific type of data source, CRIS systems"

It is surprisingly hard to find the definition for this term, especially within the OpenAIRE specifications that should aim to make information more accessible.

Would it be possible to clearly define the `CRIS` acronym? 

At least in this GitHub repository, even if it should be clear on openaire.eu too, so that users can understand it easily without needing for extended search

Thanks

**Comment by vemonet** [comment]
Found the exact meaning of the acronym here for those who were still wondering:
https://www.eurocris.org/news/openaire-guidelines-cris-managers-released

"Current Research Information Systems"

**Comment by ACz-UniBi** [comment]
Dear Vemonet,

thank you for pointing this out more prominently.
Over all you can take also a look into:

https://en.wikipedia.org/wiki/Current_research_information_system

Best, Andreas
