### ISSUE TITLE
Absence of any "Date" element in "Product"

### ISSUE THREAD

**Issue by jpiscanc** [openaire/guidelines-cris-managers#84]
There isn't any **Date element** in _"Product"_
It's a big issue!

Any IssuedDate or PublicationDate would be necessary with
use: optional (0..1) like for:
https://openaire-guidelines-for-cris-managers.readthedocs.io/en/v1.1.1/cerif_xml_publication_entity.html#publicationdate

**Comment by ACz-UniBi** [comment]
Dear @jpiscanc , 

what motivation and what meaning is behind "PublicationDate" in "Product"? 
Where do you have the date information in the CERIF model: https://eurocris.org/Uploads/Web%20pages/CERIF-1.6/documentation/MImage.html ?

Do you mean the publicationDate as a releaseDate for a Product, like a startDate?   Do you consider an endDate?    

Best regards, Andreas

**Comment by jpiscanc** [comment]
Yes I confirm: I mean it as a
_releaseDate_ for a Product, like a _startDate_.
An _endDate_ could be also considered, but I haven't now any UseCase.

I have some UseCase examples where the "_publicationDate/releaseDate_" is used.
Example of a Product (Item) that has an IssueDate
in the meaning of a "releaseDate/startDate" 
https://www.openstarts.units.it/handle/10077/29079
mapped on the CrisManagers OAI output:
https://www.openstarts.units.it/dspace-oai/openairecris?verb=GetRecord&metadataPrefix=oai_cerif_openaire&identifier=oai:www.openstarts.units.it:Products/10077/29079

Than this Product lose any "date" reference when harvested and exposed on:
https://ricerca.unityfvg.it/handle/10077/29079

I'm aware that the PublDate in the CERIF model: 
https://eurocris.org/Uploads/Web%20pages/CERIF-1.6/documentation/MImage.html 
is not defined in ResultProduct -> cfResProd
like it's defined in ResultsPublication 
in cfResPubl the cfRes-PublDate

I think that it will be important to add it.

Best regards
Jordan

**Comment by jdvorak001** [comment]
Yes, there is no date attribute in the CERIF ResultProduct entity, and that's a good thing.
As agreed in #88, the better approach is to define date elements that will be specific to different states of the product and map them to the StartDates of the ResultProduct classifications with corresponding semantic vocabulary terms. 

E.g. a `<PublishedDate>` XML element could map to the StartDate of a classification with the status Published from a tentative ProductStatuses vocabulary.

**Comment by abollini** [comment]
@jdvorak001 can you take a look to https://github.com/openaire/guidelines-cris-managers/pull/89 it would be nice if we can unblock this issue

**Comment by jdvorak001** [comment]
Yes, that one was merged and is now visible in [the "latest" build on readthedocs.org](https://openaire-guidelines-for-cris-managers.readthedocs.io/en/latest/cerif_xml_patent_entity.html).  Thank you @abollini for that contribution.

Can we think of any dates that would make sense on Products? (At least on some notable types of products – we have upgraded the typology to COAR Resource Types v.3.0 in the meantime (#99).)
Would it be PublicationDate and OpenAvailabilityDate? 
Your views, @jpiscanc and @abollini ?

**Comment by abollini** [comment]
hi @jdvorak001 it seems that this issue was forgotten at different times by all of us ;) to avoid this to happen again can we tag this for the 1.1.2 release?
PublicationDate is for sure the most urgent but I also found very important the availability of a collected date. The Datacite metadata have already defined a list of possible date qualifier and they have been adopted by OpenAIRE in the draft guidelines for Data Archive, see https://openaire-guidelines-for-data-archive-managers.readthedocs.io/en/latest/field_date.html#attribute-datetype-m-1

**Comment by jpiscanc** [comment]
Hi @jdvorak001  & @abollini 
I realy hope that this Issue could be taged for the 1.1.2 release in short time. 
It will be possible?!

**Comment by ACz-UniBi** [comment]
> Would it be PublicationDate and OpenAvailabilityDate? Your views, @jpiscanc and @abollini ?

The `date` element in [OpenAIRE Guidelines v4](https://openaire-guidelines-for-literature-repository-managers.readthedocs.io/en/latest/field_publicationdate.html#) is adapted from DataCite schema and have an attribute `dateType` with three values from [controlled vocabulary](https://openaire-guidelines-for-literature-repository-managers.readthedocs.io/en/latest/vocab_datetype.html#vocab-datetype-datetype).

Similar to v4 the 'Issued' value is the _publishedDate_ - date that the resource is published or distributed - and 'Accepted' the  _uploadedDate_. Another added value could be 'Collected' which indicates the date or date range in which the resource
content was collected.

**Comment by jdvorak001** [comment]
(recording a discussion with @ACz-UniBi)

The general mechanism for implementing this will be using the cfResProd_Class (the classifications of Result Products). The cfStartDate will be used in all cases; the cfEndDate would come into play when a date range is to be recorded. The semantic layer should then contain the specific terms that would correspond to the relevant lifecycle phases of the product. It is difficult to come up with a complete list (noting that the COAR Resource Type [other](http://purl.org/coar/resource_type/c_1843) is also represented under this entity), but an approach we're suggesting is to start with the DataCite Metadata Kernel "dateType" list and expand later.

At the CERIF-XML level this would mean a couple of elements (all optional) with startDate and endDate attributes, such as
```
<collected startDate="2021-01-01" endDate="2021-12-31"/>
```
(The XML namespace may also be a different one, we'll see.)

**Comment by abollini** [comment]
I agree to follow the datacite dateType list. Would be easier to just use the same structure than datacite? maybe keeping the Uppercase for the element name and the startDate/endDate attributes to be more aligned with our current scheme?

`
<Dates>
    <Date dateType="..." startDate="..." endDate="..." />
    <Date dateType="..." startDate="..." endDate="..." />
</Dates>
`
in this way we can easily update our guidelines with the datacite schema and it would be easier/more familiar for adopter that already implement the datacite xml format
