### ISSUE TITLE
COAR vocabulary of access_rights has different descriptions

### ISSUE THREAD

**Issue by ACz-UniBi** [openaire/guidelines-cris-managers#86]
The access_rights in the guidelines (e.g. https://openaire-guidelines-for-cris-managers.readthedocs.io/en/v1.1.1/cerif_xml_publication_entity.html#ns4-access) refers to the COAR vocabulary. The description differs.

OpenAIRE - open access:
`Open access refers to a resource that is immediately and permanently online, and free for all on the Web, without financial and technical barriers.`

COAR - open access (http://vocabularies.coar-repositories.org/access_right/c_abf2.html):
`Open access refers to a resource that is immediately and permanently online, and free for all on the Web, without financial and technical barriers.The resource is either stored in the repository or referenced to an external journal or trustworthy archive.`

Should be updated?

**Comment by jdvorak001** [comment]
The version we're currently having in the Guidelines originated from [coar_accessrights_skos-xl_20042017012634.rdf](https://github.com/coar-repositories/vocabularies/blob/master/access_rights/snapshot/coar_accessrights_skos-xl_20042017012634.rdf), see [this commit](https://github.com/openaire/guidelines-cris-managers/commit/b1ff95345c250472409af03f1c72842d595e8ba9#diff-97caef0cdddda69fd2b6c0c3563bc1d4). 

That's three years ago. Indeed it's time for an update!

**Comment by jdvorak001** [comment]
@ACz-UniBi, could you please have a look at #87 ? If you think it fixes the issue that was raised, I'll merge and close this issue.
