### ISSUE TITLE
Person Identifier - Peruvian DNI 

### ISSUE THREAD

**Issue by abollini** [openaire/guidelines-cris-managers#91]
Which is the best approach to support the Peruvian DNI? https://www.perutelegraph.com/glossary-terms-peru/dni-peru-s-national-id-card
should we add a new specific element or should we introduce a generic National Identifier with an attribute that allow to specify the country where such identifier apply? this would allow other national system to reuse this element without the need to extend the vocabulary again and again

**Comment by jdvorak001** [comment]
We (@abollini, @chenejac, @jdvorak001) discussed several options:
(1) Add explicit XML element (possibly with a regexp constraint).
(2) Extend the CERIF IdentifierTypes vocabulary with a specific item for the Peruvian DNI.
(3) Rely on an external authority to provide URIs to identify the type of the identifier. Wikidata seems to be a good candidate here. It would be https://www.wikidata.org/wiki/Q5797148 for the Peruvian DNI.

We agreed on option (3) as the most scalable and flexible one, and mention this explicitly in the documentation and illustrate it in an example. For this we need to add the generic ``<Identifier>`` construct in the XML Schema.

**Comment by jdvorak001** [comment]
I need to add the generic `<Identifier>` construct.

**Comment by jdvorak001** [comment]
Adding the generic `<Identifier>` with the following description:
> A generic identifier, to be used only if your identifier does not fit in any of the above specific identifier types. This in particular applies to various national and service-specific identifiers that can be relevant in some interchange scenarios.
